-- ============================================================
-- PMG CONNECT — CENTRAL DE ACOMPANHAMENTO V1
-- Controle Marcos + Controle Marketing / Fornecedores
-- ============================================================
-- Execute DEPOIS de demandas_supabase.sql.
-- O script e idempotente e pode ser executado novamente.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- TABELAS
-- ------------------------------------------------------------

create table if not exists public.acompanhamento_registros (
  id uuid primary key default gen_random_uuid(),
  codigo bigint generated by default as identity,
  controle text not null default 'marketing',
  ano_referencia integer not null default extract(year from current_date)::integer,
  fornecedor text,
  fornecedor_codigo text,
  categoria text not null default 'outro',
  titulo text not null,
  descricao text,
  referencia text,
  responsavel_id uuid references public.colaboradores(id) on delete set null,
  contato_nome text,
  contato_email text,
  contato_telefone text,
  status text not null default 'rascunho',
  prioridade text not null default 'normal',
  data_inicio date,
  data_fim date,
  valor_acordado numeric(14,2) not null default 0,
  centro_custo text,
  numero_documento text,
  tags text[] not null default '{}'::text[],
  observacoes text,
  origem_importacao text,
  linha_origem integer,
  fingerprint text,
  dados_originais jsonb not null default '{}'::jsonb,
  criado_por uuid references public.colaboradores(id) on delete set null,
  atualizado_por uuid references public.colaboradores(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  arquivado_em timestamptz,
  constraint acompanhamento_controle_valido check (controle in ('marcos', 'marketing')),
  constraint acompanhamento_ano_valido check (ano_referencia between 2000 and 2200),
  constraint acompanhamento_titulo_valido check (length(trim(titulo)) > 0),
  constraint acompanhamento_valor_valido check (valor_acordado >= 0),
  constraint acompanhamento_status_valido check (
    status in ('rascunho', 'negociacao', 'aprovado', 'em_andamento', 'concluido', 'cancelado')
  ),
  constraint acompanhamento_prioridade_valida check (prioridade in ('baixa', 'normal', 'alta', 'urgente')),
  constraint acompanhamento_periodo_valido check (data_fim is null or data_inicio is null or data_fim >= data_inicio)
);

create unique index if not exists idx_acompanhamento_codigo
  on public.acompanhamento_registros(codigo);
create unique index if not exists idx_acompanhamento_fingerprint
  on public.acompanhamento_registros(fingerprint)
  where fingerprint is not null and arquivado_em is null;
create index if not exists idx_acompanhamento_filtros
  on public.acompanhamento_registros(controle, ano_referencia, status, categoria)
  where arquivado_em is null;
create index if not exists idx_acompanhamento_fornecedor
  on public.acompanhamento_registros(lower(fornecedor))
  where arquivado_em is null;
create index if not exists idx_acompanhamento_responsavel
  on public.acompanhamento_registros(responsavel_id, atualizado_em desc)
  where arquivado_em is null;

create table if not exists public.acompanhamento_pagamentos (
  id uuid primary key default gen_random_uuid(),
  registro_id uuid references public.acompanhamento_registros(id) on delete cascade not null,
  parcela integer not null default 1,
  descricao text,
  valor_previsto numeric(14,2) not null default 0,
  valor_pago numeric(14,2) not null default 0,
  vencimento date,
  pago_em date,
  status text not null default 'previsto',
  forma_pagamento text,
  favorecido text,
  numero_documento text,
  observacoes text,
  fingerprint text,
  criado_por uuid references public.colaboradores(id) on delete set null,
  atualizado_por uuid references public.colaboradores(id) on delete set null,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint acompanhamento_pagamento_parcela_valida check (parcela > 0),
  constraint acompanhamento_pagamento_valores_validos check (valor_previsto >= 0 and valor_pago >= 0),
  constraint acompanhamento_pagamento_status_valido check (
    status in ('previsto', 'solicitado', 'aprovado', 'agendado', 'pago', 'cancelado')
  )
);

create unique index if not exists idx_acompanhamento_pagamento_fingerprint
  on public.acompanhamento_pagamentos(registro_id, fingerprint)
  where fingerprint is not null;
create index if not exists idx_acompanhamento_pagamentos_vencimento
  on public.acompanhamento_pagamentos(vencimento, status);
create index if not exists idx_acompanhamento_pagamentos_registro
  on public.acompanhamento_pagamentos(registro_id, parcela);

create table if not exists public.acompanhamento_anexos (
  id uuid primary key default gen_random_uuid(),
  registro_id uuid references public.acompanhamento_registros(id) on delete cascade not null,
  pagamento_id uuid references public.acompanhamento_pagamentos(id) on delete cascade,
  nome text not null,
  caminho text not null unique,
  mime_type text,
  tamanho_bytes bigint,
  tipo text not null default 'documento',
  criado_por uuid references public.colaboradores(id) on delete set null,
  criado_em timestamptz not null default now(),
  constraint acompanhamento_anexo_nome_valido check (length(trim(nome)) > 0),
  constraint acompanhamento_anexo_tipo_valido check (tipo in ('contrato', 'boleto', 'nota_fiscal', 'comprovante', 'proposta', 'documento')),
  constraint acompanhamento_anexo_tamanho_valido check (tamanho_bytes is null or tamanho_bytes >= 0)
);

create index if not exists idx_acompanhamento_anexos_registro
  on public.acompanhamento_anexos(registro_id, criado_em desc);

create table if not exists public.acompanhamento_atividades (
  id bigint generated by default as identity primary key,
  registro_id uuid references public.acompanhamento_registros(id) on delete cascade not null,
  pagamento_id uuid references public.acompanhamento_pagamentos(id) on delete cascade,
  ator_id uuid references public.colaboradores(id) on delete set null,
  tipo text not null,
  resumo text not null,
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists idx_acompanhamento_atividades_registro
  on public.acompanhamento_atividades(registro_id, criado_em desc);
create index if not exists idx_acompanhamento_atividades_recentes
  on public.acompanhamento_atividades(criado_em desc);

create table if not exists public.acompanhamento_importacoes (
  id uuid primary key default gen_random_uuid(),
  controle text not null,
  ano_referencia integer,
  nome_arquivo text not null,
  total_linhas integer not null default 0,
  linhas_criadas integer not null default 0,
  linhas_atualizadas integer not null default 0,
  linhas_ignoradas integer not null default 0,
  erros jsonb not null default '[]'::jsonb,
  criado_por uuid references public.colaboradores(id) on delete set null,
  criado_em timestamptz not null default now(),
  constraint acompanhamento_importacao_controle_valido check (controle in ('marcos', 'marketing'))
);

-- ------------------------------------------------------------
-- FUNCOES AUXILIARES
-- ------------------------------------------------------------

create or replace function public.acompanhamento_colaborador_ativo()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(exists(
    select 1 from public.colaboradores c
    where c.auth_user_id = auth.uid() and c.ativo = true
  ), false);
$$;

create or replace function public.set_acompanhamento_atualizado_em()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.atualizado_em := now();
  return new;
end;
$$;

drop trigger if exists trg_acompanhamento_registros_atualizado on public.acompanhamento_registros;
create trigger trg_acompanhamento_registros_atualizado
before update on public.acompanhamento_registros
for each row execute function public.set_acompanhamento_atualizado_em();

drop trigger if exists trg_acompanhamento_pagamentos_atualizado on public.acompanhamento_pagamentos;
create trigger trg_acompanhamento_pagamentos_atualizado
before update on public.acompanhamento_pagamentos
for each row execute function public.set_acompanhamento_atualizado_em();

-- ------------------------------------------------------------
-- VISAO CONSOLIDADA
-- ------------------------------------------------------------

create or replace view public.acompanhamento_painel
with (security_invoker = true)
as
select
  r.*,
  coalesce(p.total_previsto, 0)::numeric(14,2) as total_previsto,
  coalesce(p.total_pago, 0)::numeric(14,2) as total_pago,
  greatest(coalesce(p.total_previsto, r.valor_acordado) - coalesce(p.total_pago, 0), 0)::numeric(14,2) as saldo_aberto,
  coalesce(p.quantidade_pagamentos, 0)::integer as quantidade_pagamentos,
  coalesce(p.pagamentos_pagos, 0)::integer as pagamentos_pagos,
  p.proximo_vencimento,
  coalesce(p.pagamentos_atrasados, 0)::integer as pagamentos_atrasados,
  case
    when r.status = 'cancelado' then 'cancelado'
    when coalesce(p.quantidade_pagamentos, 0) = 0 then 'sem_pagamentos'
    when coalesce(p.pagamentos_atrasados, 0) > 0 then 'atrasado'
    when coalesce(p.total_pago, 0) >= coalesce(nullif(p.total_previsto, 0), r.valor_acordado) then 'pago'
    when coalesce(p.total_pago, 0) > 0 then 'parcial'
    else 'pendente'
  end as situacao_financeira
from public.acompanhamento_registros r
left join lateral (
  select
    sum(case when ap.status <> 'cancelado' then ap.valor_previsto else 0 end) as total_previsto,
    sum(case when ap.status = 'pago' then greatest(ap.valor_pago, ap.valor_previsto) else ap.valor_pago end) as total_pago,
    count(*) filter (where ap.status <> 'cancelado') as quantidade_pagamentos,
    count(*) filter (where ap.status = 'pago') as pagamentos_pagos,
    min(ap.vencimento) filter (where ap.status not in ('pago', 'cancelado')) as proximo_vencimento,
    count(*) filter (where ap.status not in ('pago', 'cancelado') and ap.vencimento < current_date) as pagamentos_atrasados
  from public.acompanhamento_pagamentos ap
  where ap.registro_id = r.id
) p on true
where r.arquivado_em is null;

-- ------------------------------------------------------------
-- RPC: CADASTRAR / EDITAR REGISTRO
-- ------------------------------------------------------------

create or replace function public.salvar_acompanhamento_v1(
  p_registro_id uuid,
  p_dados jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ator uuid := public.meu_colaborador_id();
  v_id uuid := p_registro_id;
  v_titulo text := trim(coalesce(p_dados ->> 'titulo', ''));
  v_controle text := coalesce(nullif(p_dados ->> 'controle', ''), 'marketing');
  v_antes jsonb;
begin
  if v_ator is null then raise exception 'Colaborador nao encontrado ou inativo'; end if;
  if v_titulo = '' then raise exception 'O titulo e obrigatorio'; end if;
  if v_controle not in ('marcos', 'marketing') then raise exception 'Controle invalido'; end if;

  if v_id is null then
    insert into public.acompanhamento_registros (
      controle, ano_referencia, fornecedor, fornecedor_codigo, categoria, titulo,
      descricao, referencia, responsavel_id, contato_nome, contato_email,
      contato_telefone, status, prioridade, data_inicio, data_fim, valor_acordado,
      centro_custo, numero_documento, tags, observacoes, origem_importacao,
      linha_origem, fingerprint, dados_originais, criado_por, atualizado_por
    ) values (
      v_controle,
      coalesce((p_dados ->> 'ano_referencia')::integer, extract(year from current_date)::integer),
      nullif(trim(p_dados ->> 'fornecedor'), ''),
      nullif(trim(p_dados ->> 'fornecedor_codigo'), ''),
      coalesce(nullif(trim(p_dados ->> 'categoria'), ''), 'outro'),
      v_titulo,
      nullif(trim(p_dados ->> 'descricao'), ''),
      nullif(trim(p_dados ->> 'referencia'), ''),
      nullif(p_dados ->> 'responsavel_id', '')::uuid,
      nullif(trim(p_dados ->> 'contato_nome'), ''),
      nullif(trim(p_dados ->> 'contato_email'), ''),
      nullif(trim(p_dados ->> 'contato_telefone'), ''),
      coalesce(nullif(p_dados ->> 'status', ''), 'rascunho'),
      coalesce(nullif(p_dados ->> 'prioridade', ''), 'normal'),
      nullif(p_dados ->> 'data_inicio', '')::date,
      nullif(p_dados ->> 'data_fim', '')::date,
      greatest(coalesce(nullif(p_dados ->> 'valor_acordado', '')::numeric, 0), 0),
      nullif(trim(p_dados ->> 'centro_custo'), ''),
      nullif(trim(p_dados ->> 'numero_documento'), ''),
      coalesce(array(select jsonb_array_elements_text(coalesce(p_dados -> 'tags', '[]'::jsonb))), '{}'::text[]),
      nullif(trim(p_dados ->> 'observacoes'), ''),
      nullif(trim(p_dados ->> 'origem_importacao'), ''),
      nullif(p_dados ->> 'linha_origem', '')::integer,
      nullif(trim(p_dados ->> 'fingerprint'), ''),
      coalesce(p_dados -> 'dados_originais', '{}'::jsonb),
      v_ator, v_ator
    ) returning id into v_id;

    insert into public.acompanhamento_atividades(registro_id, ator_id, tipo, resumo, detalhes)
    values (v_id, v_ator, 'criado', 'criou o acompanhamento', jsonb_build_object('controle', v_controle));
  else
    select to_jsonb(r) into v_antes
    from public.acompanhamento_registros r
    where r.id = v_id and r.arquivado_em is null;
    if v_antes is null then raise exception 'Acompanhamento nao encontrado'; end if;

    update public.acompanhamento_registros set
      controle = v_controle,
      ano_referencia = coalesce((p_dados ->> 'ano_referencia')::integer, ano_referencia),
      fornecedor = nullif(trim(p_dados ->> 'fornecedor'), ''),
      fornecedor_codigo = nullif(trim(p_dados ->> 'fornecedor_codigo'), ''),
      categoria = coalesce(nullif(trim(p_dados ->> 'categoria'), ''), 'outro'),
      titulo = v_titulo,
      descricao = nullif(trim(p_dados ->> 'descricao'), ''),
      referencia = nullif(trim(p_dados ->> 'referencia'), ''),
      responsavel_id = nullif(p_dados ->> 'responsavel_id', '')::uuid,
      contato_nome = nullif(trim(p_dados ->> 'contato_nome'), ''),
      contato_email = nullif(trim(p_dados ->> 'contato_email'), ''),
      contato_telefone = nullif(trim(p_dados ->> 'contato_telefone'), ''),
      status = coalesce(nullif(p_dados ->> 'status', ''), status),
      prioridade = coalesce(nullif(p_dados ->> 'prioridade', ''), prioridade),
      data_inicio = nullif(p_dados ->> 'data_inicio', '')::date,
      data_fim = nullif(p_dados ->> 'data_fim', '')::date,
      valor_acordado = greatest(coalesce(nullif(p_dados ->> 'valor_acordado', '')::numeric, 0), 0),
      centro_custo = nullif(trim(p_dados ->> 'centro_custo'), ''),
      numero_documento = nullif(trim(p_dados ->> 'numero_documento'), ''),
      tags = coalesce(array(select jsonb_array_elements_text(coalesce(p_dados -> 'tags', '[]'::jsonb))), '{}'::text[]),
      observacoes = nullif(trim(p_dados ->> 'observacoes'), ''),
      atualizado_por = v_ator
    where id = v_id;

    insert into public.acompanhamento_atividades(registro_id, ator_id, tipo, resumo, detalhes)
    values (v_id, v_ator, 'editado', 'atualizou o acompanhamento', jsonb_build_object('antes', v_antes));
  end if;

  return v_id;
end;
$$;

-- ------------------------------------------------------------
-- RPC: CADASTRAR / EDITAR PAGAMENTO
-- ------------------------------------------------------------

create or replace function public.salvar_pagamento_acompanhamento_v1(
  p_pagamento_id uuid,
  p_registro_id uuid,
  p_dados jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ator uuid := public.meu_colaborador_id();
  v_id uuid := p_pagamento_id;
  v_novo boolean := p_pagamento_id is null;
  v_status text := coalesce(nullif(p_dados ->> 'status', ''), 'previsto');
  v_valor numeric := greatest(coalesce(nullif(p_dados ->> 'valor_previsto', '')::numeric, 0), 0);
begin
  if v_ator is null then raise exception 'Colaborador nao encontrado ou inativo'; end if;
  if not exists (select 1 from public.acompanhamento_registros r where r.id = p_registro_id and r.arquivado_em is null) then
    raise exception 'Acompanhamento nao encontrado';
  end if;

  if v_id is null and nullif(trim(p_dados ->> 'fingerprint'), '') is not null then
    select ap.id into v_id
    from public.acompanhamento_pagamentos ap
    where ap.registro_id = p_registro_id
      and ap.fingerprint = nullif(trim(p_dados ->> 'fingerprint'), '')
    limit 1;
    if v_id is not null then v_novo := false; end if;
  end if;

  if v_id is null then
    insert into public.acompanhamento_pagamentos (
      registro_id, parcela, descricao, valor_previsto, valor_pago, vencimento,
      pago_em, status, forma_pagamento, favorecido, numero_documento,
      observacoes, fingerprint, criado_por, atualizado_por
    ) values (
      p_registro_id,
      greatest(coalesce(nullif(p_dados ->> 'parcela', '')::integer, 1), 1),
      nullif(trim(p_dados ->> 'descricao'), ''),
      v_valor,
      greatest(coalesce(nullif(p_dados ->> 'valor_pago', '')::numeric, case when v_status = 'pago' then v_valor else 0 end), 0),
      nullif(p_dados ->> 'vencimento', '')::date,
      nullif(p_dados ->> 'pago_em', '')::date,
      v_status,
      nullif(trim(p_dados ->> 'forma_pagamento'), ''),
      nullif(trim(p_dados ->> 'favorecido'), ''),
      nullif(trim(p_dados ->> 'numero_documento'), ''),
      nullif(trim(p_dados ->> 'observacoes'), ''),
      nullif(trim(p_dados ->> 'fingerprint'), ''),
      v_ator, v_ator
    ) returning id into v_id;
  else
    update public.acompanhamento_pagamentos set
      parcela = greatest(coalesce(nullif(p_dados ->> 'parcela', '')::integer, parcela), 1),
      descricao = nullif(trim(p_dados ->> 'descricao'), ''),
      valor_previsto = v_valor,
      valor_pago = greatest(coalesce(nullif(p_dados ->> 'valor_pago', '')::numeric, case when v_status = 'pago' then v_valor else 0 end), 0),
      vencimento = nullif(p_dados ->> 'vencimento', '')::date,
      pago_em = nullif(p_dados ->> 'pago_em', '')::date,
      status = v_status,
      forma_pagamento = nullif(trim(p_dados ->> 'forma_pagamento'), ''),
      favorecido = nullif(trim(p_dados ->> 'favorecido'), ''),
      numero_documento = nullif(trim(p_dados ->> 'numero_documento'), ''),
      observacoes = nullif(trim(p_dados ->> 'observacoes'), ''),
      atualizado_por = v_ator
    where id = v_id and registro_id = p_registro_id;
    if not found then raise exception 'Pagamento nao encontrado'; end if;
  end if;

  insert into public.acompanhamento_atividades(registro_id, pagamento_id, ator_id, tipo, resumo, detalhes)
  values (
    p_registro_id, v_id, v_ator,
    case when v_novo then 'pagamento_criado' else 'pagamento_editado' end,
    case when v_status = 'pago' then 'registrou um pagamento' else 'atualizou uma previsao de pagamento' end,
    jsonb_build_object('status', v_status, 'valor', v_valor)
  );

  return v_id;
end;
$$;

create or replace function public.arquivar_acompanhamento_v1(p_registro_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare v_ator uuid := public.meu_colaborador_id();
begin
  if v_ator is null then raise exception 'Colaborador nao encontrado ou inativo'; end if;
  update public.acompanhamento_registros
  set arquivado_em = now(), atualizado_por = v_ator
  where id = p_registro_id and arquivado_em is null;
  if not found then raise exception 'Acompanhamento nao encontrado'; end if;
  insert into public.acompanhamento_atividades(registro_id, ator_id, tipo, resumo)
  values (p_registro_id, v_ator, 'arquivado', 'arquivou o acompanhamento');
end;
$$;

create or replace function public.excluir_pagamento_acompanhamento_v1(p_pagamento_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ator uuid := public.meu_colaborador_id();
  v_registro uuid;
begin
  if v_ator is null then raise exception 'Colaborador nao encontrado ou inativo'; end if;
  delete from public.acompanhamento_pagamentos where id = p_pagamento_id returning registro_id into v_registro;
  if v_registro is null then raise exception 'Pagamento nao encontrado'; end if;
  insert into public.acompanhamento_atividades(registro_id, ator_id, tipo, resumo)
  values (v_registro, v_ator, 'pagamento_excluido', 'removeu uma previsao de pagamento');
end;
$$;

-- ------------------------------------------------------------
-- RPC: IMPORTACAO EM LOTE
-- Cada item: { registro: {...}, pagamentos: [{...}] }
-- ------------------------------------------------------------

create or replace function public.importar_acompanhamentos_v1(
  p_controle text,
  p_ano integer,
  p_nome_arquivo text,
  p_linhas jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ator uuid := public.meu_colaborador_id();
  v_importacao uuid;
  v_item jsonb;
  v_registro jsonb;
  v_pagamento jsonb;
  v_id uuid;
  v_existente uuid;
  v_criadas integer := 0;
  v_atualizadas integer := 0;
  v_ignoradas integer := 0;
  v_indice integer := 0;
  v_erros jsonb := '[]'::jsonb;
begin
  if v_ator is null then raise exception 'Colaborador nao encontrado ou inativo'; end if;
  if p_controle not in ('marcos', 'marketing') then raise exception 'Controle invalido'; end if;
  if jsonb_typeof(p_linhas) <> 'array' then raise exception 'Linhas de importacao invalidas'; end if;

  insert into public.acompanhamento_importacoes(controle, ano_referencia, nome_arquivo, total_linhas, criado_por)
  values (p_controle, p_ano, coalesce(nullif(trim(p_nome_arquivo), ''), 'planilha.xlsx'), jsonb_array_length(p_linhas), v_ator)
  returning id into v_importacao;

  for v_item in select value from jsonb_array_elements(p_linhas)
  loop
    v_indice := v_indice + 1;
    begin
      v_registro := coalesce(v_item -> 'registro', '{}'::jsonb)
        || jsonb_build_object(
          'controle', p_controle,
          'ano_referencia', coalesce((v_item -> 'registro' ->> 'ano_referencia')::integer, p_ano),
          'origem_importacao', p_nome_arquivo,
          'linha_origem', v_indice + 1
        );

      if trim(coalesce(v_registro ->> 'titulo', '')) = '' then
        v_ignoradas := v_ignoradas + 1;
        continue;
      end if;

      select r.id into v_existente
      from public.acompanhamento_registros r
      where r.fingerprint = nullif(v_registro ->> 'fingerprint', '')
        and r.arquivado_em is null
      limit 1;

      v_id := public.salvar_acompanhamento_v1(v_existente, v_registro);
      if v_existente is null then v_criadas := v_criadas + 1;
      else v_atualizadas := v_atualizadas + 1;
      end if;

      if jsonb_typeof(v_item -> 'pagamentos') = 'array' then
        for v_pagamento in select value from jsonb_array_elements(v_item -> 'pagamentos')
        loop
          perform public.salvar_pagamento_acompanhamento_v1(null, v_id, v_pagamento);
        end loop;
      end if;
    exception when others then
      v_ignoradas := v_ignoradas + 1;
      v_erros := v_erros || jsonb_build_array(jsonb_build_object('linha', v_indice + 1, 'erro', sqlerrm));
    end;
  end loop;

  update public.acompanhamento_importacoes set
    linhas_criadas = v_criadas,
    linhas_atualizadas = v_atualizadas,
    linhas_ignoradas = v_ignoradas,
    erros = v_erros
  where id = v_importacao;

  return jsonb_build_object(
    'importacao_id', v_importacao,
    'criadas', v_criadas,
    'atualizadas', v_atualizadas,
    'ignoradas', v_ignoradas,
    'erros', v_erros
  );
end;
$$;

-- ------------------------------------------------------------
-- ANEXOS
-- ------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit)
values ('acompanhamento', 'acompanhamento', false, 15728640)
on conflict (id) do update set public = false, file_size_limit = 15728640;

create or replace function public.registrar_anexo_acompanhamento_v1(
  p_registro_id uuid,
  p_pagamento_id uuid,
  p_nome text,
  p_caminho text,
  p_mime_type text,
  p_tamanho_bytes bigint,
  p_tipo text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ator uuid := public.meu_colaborador_id();
  v_id uuid;
begin
  if v_ator is null then raise exception 'Colaborador nao encontrado ou inativo'; end if;
  insert into public.acompanhamento_anexos(
    registro_id, pagamento_id, nome, caminho, mime_type, tamanho_bytes, tipo, criado_por
  ) values (
    p_registro_id, p_pagamento_id, trim(p_nome), trim(p_caminho), nullif(p_mime_type, ''),
    p_tamanho_bytes, coalesce(nullif(p_tipo, ''), 'documento'), v_ator
  ) returning id into v_id;
  insert into public.acompanhamento_atividades(registro_id, pagamento_id, ator_id, tipo, resumo, detalhes)
  values (p_registro_id, p_pagamento_id, v_ator, 'anexo', 'adicionou um documento', jsonb_build_object('nome', p_nome));
  return v_id;
end;
$$;

-- ------------------------------------------------------------
-- RLS / PERMISSOES
-- ------------------------------------------------------------

alter table public.acompanhamento_registros enable row level security;
alter table public.acompanhamento_pagamentos enable row level security;
alter table public.acompanhamento_anexos enable row level security;
alter table public.acompanhamento_atividades enable row level security;
alter table public.acompanhamento_importacoes enable row level security;

drop policy if exists "equipe le acompanhamentos" on public.acompanhamento_registros;
create policy "equipe le acompanhamentos" on public.acompanhamento_registros
for select to authenticated using (public.acompanhamento_colaborador_ativo());

drop policy if exists "equipe le pagamentos" on public.acompanhamento_pagamentos;
create policy "equipe le pagamentos" on public.acompanhamento_pagamentos
for select to authenticated using (public.acompanhamento_colaborador_ativo());

drop policy if exists "equipe le anexos" on public.acompanhamento_anexos;
create policy "equipe le anexos" on public.acompanhamento_anexos
for select to authenticated using (public.acompanhamento_colaborador_ativo());

drop policy if exists "equipe le atividades" on public.acompanhamento_atividades;
create policy "equipe le atividades" on public.acompanhamento_atividades
for select to authenticated using (public.acompanhamento_colaborador_ativo());

drop policy if exists "equipe le importacoes" on public.acompanhamento_importacoes;
create policy "equipe le importacoes" on public.acompanhamento_importacoes
for select to authenticated using (public.acompanhamento_colaborador_ativo());

drop policy if exists "equipe envia arquivos acompanhamento" on storage.objects;
create policy "equipe envia arquivos acompanhamento" on storage.objects
for insert to authenticated
with check (
  bucket_id = 'acompanhamento'
  and public.acompanhamento_colaborador_ativo()
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "equipe le arquivos acompanhamento" on storage.objects;
create policy "equipe le arquivos acompanhamento" on storage.objects
for select to authenticated
using (bucket_id = 'acompanhamento' and public.acompanhamento_colaborador_ativo());

drop policy if exists "autor remove arquivos acompanhamento" on storage.objects;
create policy "autor remove arquivos acompanhamento" on storage.objects
for delete to authenticated
using (
  bucket_id = 'acompanhamento'
  and public.acompanhamento_colaborador_ativo()
  and ((storage.foldername(name))[1] = auth.uid()::text or public.sou_gestor())
);

revoke all on public.acompanhamento_registros from anon, authenticated;
revoke all on public.acompanhamento_pagamentos from anon, authenticated;
revoke all on public.acompanhamento_anexos from anon, authenticated;
revoke all on public.acompanhamento_atividades from anon, authenticated;
revoke all on public.acompanhamento_importacoes from anon, authenticated;

grant select on public.acompanhamento_registros to authenticated;
grant select on public.acompanhamento_pagamentos to authenticated;
grant select on public.acompanhamento_anexos to authenticated;
grant select on public.acompanhamento_atividades to authenticated;
grant select on public.acompanhamento_importacoes to authenticated;
grant select on public.acompanhamento_painel to authenticated;
grant usage, select on sequence public.acompanhamento_registros_codigo_seq to authenticated;
grant usage, select on sequence public.acompanhamento_atividades_id_seq to authenticated;

grant execute on function public.acompanhamento_colaborador_ativo() to authenticated;
grant execute on function public.salvar_acompanhamento_v1(uuid, jsonb) to authenticated;
grant execute on function public.salvar_pagamento_acompanhamento_v1(uuid, uuid, jsonb) to authenticated;
grant execute on function public.arquivar_acompanhamento_v1(uuid) to authenticated;
grant execute on function public.excluir_pagamento_acompanhamento_v1(uuid) to authenticated;
grant execute on function public.importar_acompanhamentos_v1(text, integer, text, jsonb) to authenticated;
grant execute on function public.registrar_anexo_acompanhamento_v1(uuid, uuid, text, text, text, bigint, text) to authenticated;

-- Realtime para atualizacao simultanea entre Marcos e Marketing.
do $$
begin
  alter publication supabase_realtime add table public.acompanhamento_registros;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.acompanhamento_pagamentos;
exception when duplicate_object then null;
end $$;

-- FIM
