-- 41-FECHAMENTO-FORNECEDORES.sql
--
-- Aba "Fechamento" (Demandas) + dashboard leve do fornecedor.
--
-- Por que existe:
--   Todo mês o marketing atualiza ~45 planilhas de 16 MB (aba Base oculta +
--   Dashboard em Power Pivot) e manda link do WeTransfer pra cada fornecedor.
--   Agora o export do CRM (relatório "Pedidos de Vendas por Vendedor e
--   Produto") é lido no navegador, RESUMIDO (mês × produto × segmento ×
--   cliente) e publicado como 1 JSON por fornecedor no Storage.
--
-- Por que JSON no Storage e não linhas no banco:
--   O banco do plano grátis está em ~489 MB de 500 MB. Linha bruta de pedido
--   (~700 bytes cada) estouraria na hora. O Storage tem cota própria (1 GB) e
--   o resumo de um fornecedor grande (Vale do Pardo, 134 mil linhas) fica em
--   poucas centenas de KB.
--
-- Segurança:
--   * Tabelas novas: só colaborador ATIVO e SEM acesso_restrito (equipe de
--     marketing). Marcos (acesso_restrito = 'acompanhamento') não entra.
--   * E-mails e slugs NÃO ficam na tabela `fornecedores`, porque ela tem
--     policy de INSERT/UPDATE liberada pra anon (achado separado, não mexido
--     aqui) e SELECT público.
--   * Bucket `fornecedor-dashboards` é público para LEITURA DIRETA do arquivo
--     (a página do fornecedor não tem login). O nome do arquivo é o slug com
--     sufixo aleatório (ex.: tirolez-k8f3x9q2.json), então não dá pra chutar.
--     Não existe policy de SELECT pra anon em storage.objects, então ninguém
--     de fora consegue LISTAR o bucket. Escrita só pela equipe.
--
-- Idempotente: pode rodar mais de uma vez.

-- ───────────────────────── helper de permissão ─────────────────────────
create or replace function public.fechamento_equipe()
returns boolean
language sql
stable
security definer
set search_path to ''
as $$
  select coalesce(exists(
    select 1 from public.colaboradores c
    where c.auth_user_id = auth.uid()
      and c.ativo = true
      and c.acesso_restrito is null
  ), false);
$$;

revoke all on function public.fechamento_equipe() from public, anon;
grant execute on function public.fechamento_equipe() to authenticated;

-- ───────────────────────── fornecedores do fechamento ─────────────────────────
create table if not exists public.fechamento_fornecedores (
  id                        bigint generated by default as identity primary key,
  nome                      text not null unique,
  slug_publico              text not null unique
                              check (slug_publico ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and length(slug_publico) between 6 and 80),
  emails_para               text[] not null default '{}',
  emails_cc                 text[] not null default '{}',
  nomes_crm                 text[] not null default '{}',
  arquivo_template          text,
  ativo                     boolean not null default true,
  observacoes               text,
  dashboard_atualizado_em   timestamptz,
  dashboard_mes_inicial     date,
  dashboard_mes_final       date,
  dashboard_bytes           integer,
  criado_em                 timestamptz not null default now(),
  atualizado_em             timestamptz not null default now(),
  atualizado_por            uuid default auth.uid()
);

comment on table public.fechamento_fornecedores is
  'Fornecedores da aba Fechamento: contatos do e-mail mensal, aliases do CRM e metadados do dashboard publicado em storage fornecedor-dashboards/<slug_publico>.json';

-- ───────────────────────── débitos digitados por competência ─────────────────────────
create table if not exists public.fechamento_debitos (
  id              uuid primary key default gen_random_uuid(),
  fornecedor_id   bigint not null references public.fechamento_fornecedores(id) on delete cascade,
  competencia     date not null check (extract(day from competencia) = 1),
  itens           jsonb not null default '[]'::jsonb check (jsonb_typeof(itens) = 'array'),
  observacao      text,
  enviado_em      timestamptz,
  enviado_por     uuid,
  criado_em       timestamptz not null default now(),
  atualizado_em   timestamptz not null default now(),
  atualizado_por  uuid default auth.uid(),
  unique (fornecedor_id, competencia)
);

comment on column public.fechamento_debitos.itens is
  'Linhas da tabela DÉBITOS do e-mail: [{"descricao":"PLANO","referente":39131.09,"pendente":39131.09}]';

-- ───────────────────────── log de uploads (auditoria) ─────────────────────────
create table if not exists public.fechamento_uploads (
  id               uuid primary key default gen_random_uuid(),
  fornecedor_id    bigint not null references public.fechamento_fornecedores(id) on delete cascade,
  tipo             text not null check (tipo in ('crm','template')),
  arquivo_nome     text not null,
  nome_crm         text,
  mes_inicial      date not null,
  mes_final        date not null,
  linhas           integer not null default 0,
  total_venda      numeric(16,2) not null default 0,
  total_relatorio  numeric(16,2),
  enviado_por      uuid default auth.uid(),
  criado_em        timestamptz not null default now(),
  check (mes_final >= mes_inicial)
);

create index if not exists fechamento_uploads_fornecedor_idx
  on public.fechamento_uploads (fornecedor_id, criado_em desc);

-- ───────────────────────── atualizado_em / atualizado_por ─────────────────────────
create or replace function public.fechamento_touch()
returns trigger
language plpgsql
set search_path to ''
as $$
begin
  new.atualizado_em = now();
  new.atualizado_por = auth.uid();
  return new;
end;
$$;

drop trigger if exists fechamento_fornecedores_touch on public.fechamento_fornecedores;
create trigger fechamento_fornecedores_touch before update on public.fechamento_fornecedores
  for each row execute procedure public.fechamento_touch();

drop trigger if exists fechamento_debitos_touch on public.fechamento_debitos;
create trigger fechamento_debitos_touch before update on public.fechamento_debitos
  for each row execute procedure public.fechamento_touch();

-- ───────────────────────── RLS ─────────────────────────
alter table public.fechamento_fornecedores enable row level security;
alter table public.fechamento_debitos      enable row level security;
alter table public.fechamento_uploads      enable row level security;

revoke all on public.fechamento_fornecedores, public.fechamento_debitos, public.fechamento_uploads from anon;

do $$
declare t text;
begin
  foreach t in array array['fechamento_fornecedores','fechamento_debitos','fechamento_uploads'] loop
    execute format('drop policy if exists "equipe le %1$s" on public.%1$I', t);
    execute format('drop policy if exists "equipe cria %1$s" on public.%1$I', t);
    execute format('drop policy if exists "equipe edita %1$s" on public.%1$I', t);
    execute format('drop policy if exists "gestor remove %1$s" on public.%1$I', t);
    execute format('create policy "equipe le %1$s" on public.%1$I for select to authenticated using (public.fechamento_equipe())', t);
    execute format('create policy "equipe cria %1$s" on public.%1$I for insert to authenticated with check (public.fechamento_equipe())', t);
    if t <> 'fechamento_uploads' then
      execute format('create policy "equipe edita %1$s" on public.%1$I for update to authenticated using (public.fechamento_equipe()) with check (public.fechamento_equipe())', t);
    end if;
    execute format('create policy "gestor remove %1$s" on public.%1$I for delete to authenticated using (public.fechamento_equipe() and public.sou_gestor())', t);
  end loop;
end $$;

-- (log de upload não tem policy de UPDATE: não é editável depois de gravado)

-- ───────────────────────── bucket do dashboard ─────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('fornecedor-dashboards', 'fornecedor-dashboards', true, 5242880, array['application/json'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "equipe le dashboards fornecedor" on storage.objects;
drop policy if exists "equipe publica dashboards fornecedor" on storage.objects;
drop policy if exists "equipe atualiza dashboards fornecedor" on storage.objects;
drop policy if exists "equipe remove dashboards fornecedor" on storage.objects;

create policy "equipe le dashboards fornecedor" on storage.objects
  for select to authenticated
  using (bucket_id = 'fornecedor-dashboards' and public.fechamento_equipe());

create policy "equipe publica dashboards fornecedor" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'fornecedor-dashboards' and public.fechamento_equipe());

create policy "equipe atualiza dashboards fornecedor" on storage.objects
  for update to authenticated
  using (bucket_id = 'fornecedor-dashboards' and public.fechamento_equipe())
  with check (bucket_id = 'fornecedor-dashboards' and public.fechamento_equipe());

create policy "equipe remove dashboards fornecedor" on storage.objects
  for delete to authenticated
  using (bucket_id = 'fornecedor-dashboards' and public.fechamento_equipe());

-- ───────────────────────── carga inicial (planilha "E-mails Fornecedores 3") ─────────────────────────
-- Slugs gerados uma vez, com sufixo aleatório. on conflict: não sobrescreve o
-- que a equipe já editou na aba.
insert into public.fechamento_fornecedores
  (nome, slug_publico, emails_para, arquivo_template, nomes_crm, ativo, observacoes)
values
  ('Ajinomoto', 'ajinomoto-yo70i6jm', array['giovanna_souza@br.ajinomoto.com','mariana_guirado@br.ajinomoto.com','cleiton_sanchez@br.ajinomoto.com','raquel_santos@br.ajinomoto.com']::text[], 'Ajinomoto.xlsx', '{}'::text[], true, null),
  ('Alfama', 'alfama-jvftbkgd', array['felipe.cunha@alfama.com.br','luiz.maia@alfama.com.br','emily.silva@alfama.com.br']::text[], 'Alfama-_.xlsx', '{}'::text[], true, null),
  ('Alibra', 'alibra-tnn167oj', array['allan.almeida@alibra.com.br','camila.romero@alibra.com.br','fabiana.mazzulli@alibra.com.br','maria.narloch@alibra.com.br','tatiana.dantas@alibra.com.br']::text[], 'Alibra.xlsx', '{}'::text[], true, null),
  ('Anaconda', 'anaconda-sdhqyp93', array['ilan.lima@anaconda.com.br','isa.telles@anaconda.com.br','fabio.burim@anaconda.com.br']::text[], null, '{}'::text[], true, null),
  ('Aurora', 'aurora-0i8l49h4', array['rogerio-araujo@auroracoop.com.br','helber-moreira@auroracoop.com.br']::text[], 'Aurora.xlsx', '{}'::text[], true, null),
  ('Belarina', 'belarina-xui89n8m', array['natalia.ribeiro@belarina.com.br']::text[], null, '{}'::text[], true, null),
  ('Bem Brasil', 'bem-brasil-qwvjq2bi', array['robertocacia@terra.com.br','batatascianflone@uol.com.br']::text[], 'Bem Brasil-.xlsx', '{}'::text[], true, null),
  ('Bunge', 'bunge-cuu6hk2l', array['misael.ferreira@bunge.com','tainara.pereira@bunge.com']::text[], 'Bunge-.xlsx', '{}'::text[], true, null),
  ('Buquê', 'buque-rpn72s4v', '{}'::text[], 'Buquê.xlsx', '{}'::text[], true, null),
  ('Camil', 'camil-9fn5l344', array['ella.silva@camil.com.br','renata.lima@camil.com.br']::text[], 'Camil-.xlsx', '{}'::text[], true, null),
  ('Cargill', 'cargill-9jont882', array['igor_andrade@cargill.com','luciana_anjos@cargill.com']::text[], 'Cargill.xlsx', '{}'::text[], true, null),
  ('Cargill (contatos Orquídea)', 'cargill-ngoxdsec', array['fabio.laurino@orquidea.com.br','enlaurino@gmail.com']::text[], null, '{}'::text[], false, 'Segundo bloco "Cargill" da planilha, com e-mails @orquidea.com.br. Conferir a qual fornecedor pertence.'),
  ('Catupiry', 'catupiry-htut63ym', array['silvany@catupiry.com.br','regiane.marcal@catupiry.com.br','rodrigo.ribeiro@catupiry.com.br','camila.um@catupiry.com.br']::text[], 'Catupiry.xlsx', '{}'::text[], true, null),
  ('Cepêra', 'cepera-djpipe05', array['carlos.silva@cepera.com.br','marco.lima@cepera.com.br','jaine.goncalves@cepera.com.br']::text[], 'Cepêra.xlsx', '{}'::text[], true, null),
  ('Ceratti', 'ceratti-83nug9ml', array['evillares@ceratti.com.br','jpgoncalves@ceratti.com.br']::text[], 'Ceratti.xlsx', '{}'::text[], true, null),
  ('Clara Milk', 'clara-milk-n51g1x1e', array['margonrep@gmail.com']::text[], null, '{}'::text[], true, null),
  ('Coamo', 'coamo-i09j5z57', array['alelima@coamo.com.br']::text[], 'Coamo.xlsx', '{}'::text[], true, null),
  ('Coronata', 'coronata-kela1lp8', array['marketing@coronata.com.br','josehenrique.cordeiro@yahoo.com.br','contabilidade@coronata.com.br','caio.lima.urso@gmail.com']::text[], 'Coronata.xlsx', '{}'::text[], true, null),
  ('Ekma', 'ekma-bpyghe8y', array['cleilson.marques@marcasdmg.com.br']::text[], 'Ekma.xlsx', '{}'::text[], true, null),
  ('Frimesa', 'frimesa-f34jl3u9', array['fdsilva@frimesa.com.br','cilene_oliv31@hotmail.com']::text[], 'Frimesa.xlsx', '{}'::text[], true, null),
  ('Gomes da Costa', 'gomes-da-costa-4nn974ln', array['fabianagomes@nauterra.com.br','fernandasilva@nauterra.com.br']::text[], 'Gomes da Costa.xlsx', '{}'::text[], true, null),
  ('Granarolo', 'granarolo-qttdl8no', array['flavia.rocha@granarolo.com.br','tatiana.jones@granarolo.com.br']::text[], null, '{}'::text[], true, null),
  ('Grano', 'grano-halntsy2', array['claudia.keppler@grano.com.br','camila.dellatorre@grano.com.br','ana.medina@grano.com.br','mileny.domingues@grano.com.br']::text[], 'Grano.xlsx', '{}'::text[], true, null),
  ('Harald', 'harald-1tl8li6l', array['fabiana.silva@harald.com.br','gleide.silva@harald.com.br']::text[], 'Harald.xlsx', '{}'::text[], true, null),
  ('Heinz', 'heinz-7fytp8uv', array['lais.machado@kraftheinz.com','fabio.loezer@kraftheinz.com','fernando.fuentes@kraftheinz.com','gabriela.viana@kraftheinz.com']::text[], 'Heinz.xlsx', '{}'::text[], true, null),
  ('Ipanema', 'ipanema-cndhm1j0', array['marcelepereira@ipanemalacteos.com.br','ricardocouto@ipanemalacteos.com.br']::text[], null, '{}'::text[], true, null),
  ('Italac', 'italac-lfrfgxyo', array['nilson.silva@italac.com.br','pealitalac@gmail.com']::text[], 'Italac.xlsx', '{}'::text[], true, null),
  ('J.Macêdo', 'j-macedo-te84d1z7', array['edvaldopereira@jmacedo.com.br','stellasimionato@jmacedo.com.br','jaquelinelima@jmacedo.com.br']::text[], 'J.Macêdo.xlsx', '{}'::text[], true, null),
  ('LambWeston', 'lambweston-q34lmncr', array['julio.petroni@lambweston.com']::text[], 'LambWeston.xlsx', '{}'::text[], true, null),
  ('McCain', 'mccain-67my0xn5', array['david.dossantossilva@mccain.com.br','marco.pereira@mccain.com.br','gabriela.sperandio@fornodeminas.com.br']::text[], 'McCain-_.xlsx', '{}'::text[], true, null),
  ('Mirella', 'mirella-008s18vo', array['fabio.laurino@ocrim.com.br','enlaurino@gmail.com']::text[], 'Mirella-.xlsx', '{}'::text[], true, null),
  ('Mr. Beef', 'mr-beef-vbp3w26o', array['lpmrepresentacoes@uol.com.br']::text[], 'Mr. Beef.xlsx', '{}'::text[], true, null),
  ('Nita', 'nita-gnlwtwtg', array['heberty.silva@nita.com.br','matheus.fernandes@nita.com.br']::text[], null, '{}'::text[], true, null),
  ('Polenghi', 'polenghi-a12uko9i', array['leandro.botelho@savencia.com','marcella.rialto@savencia.com']::text[], 'Polenghi-.xlsx', '{}'::text[], true, null),
  ('Predilecta', 'predilecta-ycj4d3u8', array['mottinelli@uol.com.br']::text[], 'Predilecta-.xlsx', '{}'::text[], true, null),
  ('Prieto', 'prieto-pflcfo9c', array['marcia.silva@prietoalimentos.com.br']::text[], 'Prieto.xlsx', '{}'::text[], true, null),
  ('Qualimax', 'qualimax-fw8bbk89', array['bruno.raga@liotecnica.com.br','weslley.nunes@liotecnica.com.br','v.pinho@uol.com.br']::text[], 'Qualimax.xlsx', '{}'::text[], true, null),
  ('Quatá', 'quata-biepb6aq', array['braulio.caccavo@quataalimentos.com.br','rui.junior@quataalimentos.com.br','saulo.campos@quataalimentos.com.br']::text[], 'Quatá.xlsx', '{}'::text[], true, null),
  ('Scala', 'scala-owh08f3y', array['suelen.vieira@scala.com.br','andre.zaminelli@scala.com.br','diego.schaberle@scala.com.br','joselma.ribeiro@scala.com.br']::text[], 'Scala.xlsx', '{}'::text[], true, null),
  ('Seara', 'seara-y0ji4b5t', array['orlando.pires@seara.com.br','ana.caradori@seara.com.br','glauco.bernini@seara.com.br','gabriela.caires@seara.com.br','giulia.tavares@seara.com.br','caroline.santamalvina@seara.com.br','simone.cruz@seara.com.br','mileny.domingues@seara.com.br']::text[], 'Seara-.xlsx', '{}'::text[], true, null),
  ('Simplot', 'simplot-cz0cqa00', array['amoraes@simplot.com.br','arthur.demoraes@simplot.com','janaina.moreno@simplot.com']::text[], 'Simplot.xlsx', '{}'::text[], true, null),
  ('Tirolez', 'tirolez-0m7kwr7o', array['rita.souza@tirolez.com.br','rafael.rosa@tirolez.com.br','miguel.dias@tirolez.com.br']::text[], 'Tirolez.xlsx', array['LATICÍNIOS TIROLEZ LTDA.']::text[], true, null),
  ('Vale do Pardo', 'vale-do-pardo-mtlv8ul8', '{}'::text[], 'Vale do Pardo.xlsx', '{}'::text[], true, null),
  ('Venturelli', 'venturelli-s8ju5f1a', array['vagner.mendes@moinhoglobo.com.br','gassantis25@gmail.com']::text[], 'Venturelli.xlsx', '{}'::text[], true, null),
  ('Yema', 'yema-ugclmg5j', array['margonrep@gmail.com']::text[], 'Yema..xlsx', '{}'::text[], true, null)
on conflict (nome) do nothing;
